models:
  - type: "sam3"
    name: "sam3_image_model"
    
    params:
      device_map: "manual"            # handled via CUDA_DEVICES
      torch_dtype: "bfloat16"         # recommended for Ampere GPUs
      use_tf32: true                  # enable TF32 for speed
      inference_mode: true            # disables gradients

    transform_params:
      random_resize_params:
        sizes: 1008
        max_size: 1008
        square: true
        consistent_transform: false
      
      normalize_params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

    postprocess_params:
      iou_type: "segm"
      detection_threshold: 0.5
      max_dets_per_img: -1
      use_original_sizes_box: true
      use_original_sizes_mask: true
      convert_mask_to_rle: false
      to_cpu: false

model_name: "sam3"

paths:
  input_folder: ""
  input_jsonl_file: "/fsxvision_new/jyothi.swaroopa/grounded_captioning_ops/ip-10-20-241-38/results_00006.jsonl"
  output_folder: "/opt/dlami/nvme/lavanya.venna/visual_grounding_outputs/outputs_gpu_7"
  mask_folder: "/opt/dlami/nvme/lavanya.venna/visual_grounding_outputs/masks_7"
  processed_file: "/opt/dlami/nvme/lavanya.venna/visual_grounding_outputs/processed_images_using_sam3_7.txt"
  prompt_path: "src/visual_grounding/prompts/entity_segmentation_prompt.yaml"
  bpe_path: "dependencies/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz"

runtime:
  CUDA_DEVICES: "7"
  batch_size: 3